credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "Used to login to Gitea source control"
          id: "GITEA_CREDENTIALS"
          password: "{AQAAABAAAABApfJ0inga7dEZ9wrAt2k8PsNRtCSGEzZ1xu8Lmfxl5AuIlUstHKV1joDH/2wDOvFVwgI6Jsb1j0lyavzmXQoR75twljl8/mf5er3btiAbAic=}"
          scope: GLOBAL
          username: "cicdservice"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy: "loggedInUsersCanDoAnything"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.diagnostics.ControllerExecutorsNoAgents"
  - "hudson.util.DoubleLaunchChecker"
  labelAtoms:
  - name: "builder"
  - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  noUsageStatistics: true
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "responseTime"
  nodes:
  - permanent:
      launcher:
        command:
          command: "docker run -i --rm --name builder --network cicdlab -v //var/run/docker.sock://var/run/docker.sock\
            \ --init mscata/cicdlabs-ciagent java -jar /usr/share/jenkins/agent.jar"
      name: "builder"
      numExecutors: 10
      remoteFS: "/home/jenkins/agent"
      retentionStrategy: "always"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 3
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
        properties:
        - "consoleUrlProvider"
        - "apiToken"
        - "favorite"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - "experimentalFlags"
        - mailer:
            emailAddress: "admin@cicdlabs.org"
      - id: "developer"
        name: "developer"
        properties:
        - "consoleUrlProvider"
        - "apiToken"
        - "favorite"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - "experimentalFlags"
        - mailer:
            emailAddress: "developer@cicdlabs.org"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  sSHD:
    port: -1
  scriptApproval:
    approvedScriptHashes:
    - "SHA512:36995a5e4c8aab21d971dd0474a576c87f3ed3a7e3d909f735d8b4e16b471dfd1078c5ebc8da369494670e28a6a4e18f8d670d37eaf8ba123d5aba002f74faf6"
    - "SHA512:998117ab61c421d7afba3bb25bf7157a39127edc0fb05dd6b9d9f0911724dffae8d9d92efdfa47d6624f049fe4b81c4a7813aa96865c76fbaee872f4081f6821"
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        enableCache: false
        manageHooks: false
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
    - simpleBuildDiscarder:
        discarder:
          logRotator:
            numToKeepStr: "10"
  buildStepOperation:
    enabled: false
  enrichedSummaryConfig:
    enrichedSummaryEnabled: false
    httpClientDelayBetweenRetriesInSeconds: 1
    httpClientMaxRetries: 3
    httpClientTimeoutInSeconds: 1
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost:8080/github-webhook/"
  giteaServers:
    servers:
    - credentialsId: "GITEA_CREDENTIALS"
      displayName: "cicdlab-scmserver"
      manageHooks: true
      serverUrl: "http://cicdlab-scmserver:3000"
  globalTimeOutConfiguration:
    operations:
    - "abortOperation"
    overwriteable: false
  injectionConfig:
    allowUntrusted: false
    checkForBuildAgentErrors: false
    enabled: false
    enforceUrl: false
    injectCcudExtension: false
    injectMavenExtension: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://localhost:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    globalConfigEmail: "jenkins@cicdlabs.org"
    globalConfigName: "ciserver"
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  shell:
    shell: "/bin/bash"
  subversionSCM:
    workspaceFormat: 8
  timestamper:
    allPipelines: true
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  warningsParsers:
    consoleLogScanningPermitted: false
tool:
  dependency-check:
    installations:
    - home: "/opt/dependency-check"
      name: "Dependency Check 8.4.0"
  dockerTool:
    installations:
    - home: "/usr"
      name: "Docker"
  git:
    installations:
    - home: "/usr/bin/git"
      name: "Default"
  gradle:
    installations:
    - home: "/opt/gradle-8.3"
      name: "Gradle 8.3"
  jdk:
    installations:
    - home: "/opt/java/openjdk"
      name: "Open JDK 17"
  maven:
    installations:
    - home: "/opt/apache-maven-3.9.4"
      name: "apache-maven-3.9.4"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
